name: Build Anaconda3 Alpine Image
on:
  push:
    paths:
      - 'anaconda3/alpine/Dockerfile'
      - '.github/workflows/anaconda_alpine_ci.yml'
  pull_request:
    paths:
      - 'anaconda3/alpine/Dockerfile'
      - '.github/workflows/anaconda_alpine_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25
        with:
          version: latest
          driver-opts: network=host

      - name: build anaconda3/alpine
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: ./anaconda3/alpine
          builder: ${{ steps.buildx.outputs.name }}
          file: ./anaconda3/alpine/Dockerfile
          tags: continuumio/anaconda3/alpine:latest
          push: false
