name: Build Anaconda3 amazonlinux Image
on:
  push:
    tags:
      - 'anaconda3-*'
    paths:
      - 'anaconda3/amazonlinux/Dockerfile'
      - '.github/workflows/anaconda_amazonlinux_ci.yml'
  pull_request:
    paths:
      - 'anaconda3/amazonlinux/Dockerfile'
      - '.github/workflows/anaconda_amazonlinux_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Login to DockerHub
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480
        with:
          platforms: linux/arm64/v8

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@f2a13332ac1ce8c0a71aeac48a150dbb1838ab67
        with:
          images: |
            continuumio/anaconda3
          tags: |
            type=ref,event=branch,suffix=-amazonlinux
            type=ref,event=pr,suffix=-amazonlinux
            type=match,pattern=anaconda3-(.*),group=1,suffix=-amazonlinux
          flavor: |
            latest=false

      - name: build-push anaconda3/amazonlinux
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: ./anaconda3/amazonlinux
          builder: ${{ steps.buildx.outputs.name }}
          file: ./anaconda3/amazonlinux/Dockerfile
          platforms: linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags') }}
